<?php
$this->headTitle($this->translate('Add Tag'));
$this->mainMenu()->setActiveItemId('tags');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')        => $this->url('home'),
    $this->translate('Manage Tags') => $this->url('tags'),
    $this->translate('Add Tag')     => $this->url('tags', ['action'=>'add'])
]);

$this->form->get('name')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Fill in the tag name')
]);

$this->form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$this->form->prepare();
?>

<h1><?= $this->translate('Add Tag')?></h1>

<p><?= $this->translate('Please fill out the following form and click the <i>Create</i> button.</p>')?></p>

<div class="row">
    <?= $this->form()->openTag($this->form); ?>
    <div class="col-md-12">
        <?= $this->formElementErrors($this->form->get('csrf')); ?>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <?= $this->formLabel($this->form->get('name')); ?>
            <?= $this->formElement($this->form->get('name')); ?>
            <?= $this->formElementErrors($this->form->get('name')); ?>
        </div>
    </div>
    <?= $this->formElement($this->form->get('csrf')); ?>
    <div class="col-md-12">
        <?= $this->formElement($this->form->get('submit')); ?>
    </div>
    <?= $this->form()->closeTag(); ?>
</div>

