<?php
$this->headTitle('Add Tag');
$this->mainMenu()->setActiveItemId('tags');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Tags'=>$this->url('tags'),
    'Add Tag'=>$this->url('tags', ['action'=>'add'])
]);

$this->form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Заполните название тега'
]);

$this->form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$this->form->prepare();
?>

<h1>Add Tag</h1>

<p>Please fill out the following form and click the <i>Create</i> button.</p>

<div class="row">
    <?= $this->form()->openTag($this->form); ?>
    <div class="col-md-12">
        <?= $this->formElementErrors($this->form->get('csrf')); ?>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <?= $this->formLabel($this->form->get('name')); ?>
            <?= $this->formElement($this->form->get('name')); ?>
            <?= $this->formElementErrors($this->form->get('name')); ?>
        </div>
    </div>
    <?= $this->formElement($this->form->get('csrf')); ?>
    <div class="col-md-12">
        <?= $this->formElement($this->form->get('submit')); ?>
    </div>
    <?= $this->form()->closeTag(); ?>
</div>

