<?php
$this->headTitle('Edit Tag');
$this->mainMenu()->setActiveItemId('tags');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Tags'=>$this->url('tags'),
    'Edit Tag'=>$this->url('tags', ['action'=>'edit', 'id'=>$this->tag->getId()])
]);

$this->form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter Name'
]);


$this->form->get('submit')
    ->setAttributes(['class'=>'btn btn-primary'])
    ->setValue('Save');

$this->form->prepare();
?>

<h1>Edit Tag</h1>

<div class="row">
    <?= $this->form()->openTag($this->form); ?>
    <div class="col-md-12">
        <?= $this->formElementErrors($this->form->get('csrf')); ?>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <?= $this->formLabel($this->form->get('name')); ?>
            <?= $this->formElement($this->form->get('name')); ?>
            <?= $this->formElementErrors($this->form->get('name')); ?>
        </div>
    </div>
    <div class="col-md-6">
        <?= $this->formElement($this->form->get('csrf')); ?>
    </div>
    <div class="col-md-12">
        <?= $this->formElement($this->form->get('submit')); ?>
    </div>
    <?= $this->form()->closeTag(); ?>
</div>

