<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('tags');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Tags'=>$this->url('tags'),
]);
?>
<div class="row">
    <div class="col-md-12">
        <h1>Manage Tags</h1>

        <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
        <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
        <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

        <p>
            <a class="btn btn-default" href="<?= $this->url('tags', ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Tag
            </a>
        </p>
    </div>
    <div class="col-md-12 scroll-x-auto">
        <table class="table table-striped table-condensed table-bordered min-width-table">

            <tr>
                <th class="column-id">ID</th>
                <th class="column-title crop">Name</th>
                <th class="column-create">Date Created</th>
                <th class="column-create">Date Updated</th>
                <th class="column-actions">Actions</th>
            </tr>

            <?php foreach ($this->tags as $post): ?>

                <tr>
                    <td class="column-id">
                        <span><?= $this->escapeHtml($post->getId()); ?></span>
                    </td>
                    <td class="column-title crop">
                        <span><?= $this->escapeHtml($post->getName()); ?></span>
                    </td>
                    <td class="column-create"><nobr><?= $this->escapeHtml($post->getDateCreated()); ?></nobr></td>
                    <td class="column-create"><nobr><?= $this->escapeHtml($post->getDateUpdated()); ?></nobr></td>
                    <td class="btn-actions-mini column-actions"><nobr>
                        <a class="btn btn-info" href="<?= $this->url('tags',
                            ['action'=>'edit', 'id'=>$post->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" ></span>
                        </a>
                        <a class="btn btn-danger" href="<?= $this->url('tags',
                            ['action'=>'delete', 'id'=>$post->getId()]); ?>">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a></nobr>
                    </td>
                </tr>

            <?php endforeach; ?>

        </table>
    </div>
    <div class="col-md-12">
        <?= $this->paginationControl(
            $this->tags,
            'Sliding',
            'application/partial/paginator',
            array('route' => 'tags')
        ); ?>
    </div>
</div>





