<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
?>

<h1>Posts</h1>

<p>
    dfgdfgfdgd
</p>

<p>
    Click the <em>Sign in</em> button at the top right. To sign in, use the
    following credentials:
    <ul>
        <li>Username: <em>admin@example.com</em></li>
        <li>Password: <em>Secur1ty</em></li>
    </ul>
</p>

<p>
    When signed in, use the <em>Admin</em> menu at the top to manage users, roles and permissions.
</p>


