<?php
$this->headTitle($this->translate('Sign in'));
$this->mainMenu()->setActiveItemId('login');

$this->form->get('email')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Email address'),
    'required'    => true,
    'autofocus'   => true
])
->setLabelAttributes(['class' => 'sr-only']);

$this->form->get('password')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Password'),
    'required'    => true,
])
->setLabelAttributes(['class' => 'sr-only']);
?>

<div class="row">
    <div class="col-md-offset-4 col-md-3">
        <form class="form-signin" method="post">
            <h2 class="form-signin-heading"><?= $this->translate('Please sign in')?></h2>
            <?php if ($this->isLoginError): ?>
            <div class="alert alert-warning" role="alert">
                <?= $this->translate('Incorrect login and/or password.')?>
                <a href="<?= $this->url('reset-password') ?>">
                    <?= $this->translate('Forgot password?')?>
                </a>
            </div>
            <?php endif; ?>
            <div class="row">
                <div class="col-md-12 mb-2">
                    <?= $this->formLabel($this->form->get('email')); ?>
                    <?= $this->formElement($this->form->get('email')); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $this->formLabel($this->form->get('password')); ?>
                    <?= $this->formElement($this->form->get('password')); ?>
                </div>
            </div>
            <div class="checkbox">
                <label>
                    <?= $this->formElement($this->form->get('remember_me')); ?>
                    <?= $this->translate('Remember me')?>
                </label>
            </div>
            <?= $this->formElement($this->form->get('redirect_url')); ?>
            <?= $this->formElement($this->form->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">
                <?= $this->translate('Sign in')?>
            </button>
        </form>
    </div>
</div>
