<?php
$this->headTitle($this->translate('Add User'));
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')         => $this->url('home'),
    $this->translate('Manage Users') => $this->url('users'),
    $this->translate('Add User')     => $this->url('users', ['action'=>'add'])
]);

$this->form->get('email')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => 'name@example.com'
]);

$this->form->get('full_name')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Enter full name')
]);

$this->form->get('status')->setAttributes([
    'class'=>'form-control'
]);

$this->form->get('password')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Enter password'),
]);

$this->form->get('confirm_password')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Retype password'),
]);

$this->form->get('roles')->setAttributes([
    'class' => 'form-control'
]);

$this->form->get('submit')
    ->setAttributes(['class'=>'btn btn-primary'])
    ->setValue($this->translate('Create'));

$this->form->prepare();
?>

<h1><?= $this->translate('Add User')?></h1>

<p>
<?= $this->translate('Please fill out the following form and click the <i>Create</i> button.');?>
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($this->form); ?>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('email')); ?>
            <?= $this->formElement($this->form->get('email')); ?>
            <?= $this->formElementErrors($this->form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('full_name')); ?>
            <?= $this->formElement($this->form->get('full_name')); ?>
            <?= $this->formElementErrors($this->form->get('full_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('password')); ?>
            <?= $this->formElement($this->form->get('password')); ?>
            <?= $this->formElementErrors($this->form->get('password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('confirm_password')); ?>
            <?= $this->formElement($this->form->get('confirm_password')); ?>
            <?= $this->formElementErrors($this->form->get('confirm_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('status')); ?>
            <?= $this->formElement($this->form->get('status')); ?>
            <?= $this->formElementErrors($this->form->get('status')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('roles')); ?>
            <?= $this->formElement($this->form->get('roles')); ?>
            <?= $this->formElementErrors($this->form->get('roles')); ?>
        </div>

        <?= $this->formElement($this->form->get('csrf')); ?>
        <?= $this->formElementErrors($this->form->get('csrf')); ?>
        <?= $this->formElement($this->form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

