<?php
$this->headTitle($this->translate('Change Password'));
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')            => $this->url('home'),
    $this->translate('Manage Users')    => $this->url('users'),
    $this->translate('Change Password') => $this->url('users', ['action'=>'change-password', 'id'=>$this->user->getId()])
]);

$this->form->get('old_password')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Enter old password')
]);

$this->form->get('new_password')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Enter new password')
]);

$this->form->get('confirm_new_password')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Re-enter new password')
]);

$this->form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$this->form->prepare();
?>

<h1><?= $this->translate('Change Password for')?> <?= $this->escapeHtml($this->user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($this->form); ?>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('old_password')); ?>
            <?= $this->formElement($this->form->get('old_password')); ?>
            <?= $this->formElementErrors($this->form->get('old_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('new_password')); ?>
            <?= $this->formElement($this->form->get('new_password')); ?>
            <?= $this->formElementErrors($this->form->get('new_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('confirm_new_password')); ?>
            <?= $this->formElement($this->form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($this->form->get('confirm_new_password')); ?>
        </div>

        <?= $this->formElement($this->form->get('csrf')); ?>

        <?= $this->formElement($this->form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>


