<?php
$this->headTitle($this->translate('Users'));
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')         => $this->url('home'),
    $this->translate('Manage Users') => $this->url('users'),
    ]);
?>


<div class="row">
    <div class="col-md-12">
        <h1><?= $this->translate('Manage Users')?></h1>
        <p>
            <a class="btn btn-default" href="<?= $this->url('users', ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                <?= $this->translate('New User');?>
            </a>
        </p>
    </div>
    <div class="col-md-12 scroll-x-auto">
        <table class="table table-striped table-condensed table-bordered min-width-table">

            <tr>
                <th class="column-id">ID</th>
                <th class="column-name"><?= $this->translate('E-mail')?></th>
                <th><?= $this->translate('Full Name')?></th>
                <th><?= $this->translate('Role(s)')?></th>
                <th class="column-status"><?= $this->translate('Status')?></th>
                <th class="column-create"><?= $this->translate('Date Created')?></th>
                <th class="column-actions"><?= $this->translate('Actions')?></th>
            </tr>

            <?php foreach ($this->users as $user): ?>

                <tr>
                    <td class="column-id"><?= $this->escapeHtml($user->getId()); ?></td>
                    <td class="column-name">
                        <a class="crop" title="<?=$user->getEmail();?>" href="<?= $this->url('users', ['action'=>'view', 'id'=>$user->getId()]); ?>">
                            <?= $this->escapeHtml($user->getEmail()); ?>
                        </a>
                    </td>
                    <td>
                        <span><?= $this->escapeHtml($user->getFullName()); ?></span>
                    </td>
                    <td>
                        <span><?= $this->escapeHtml($user->getRolesAsString()); ?></span>
                    </td>
                    <td class="column-status"><span><?= $this->escapeHtml($user->getStatusAsString()); ?></span></td>
                    <td class="column-create"><nobr><?= $this->escapeHtml($user->getDateCreated()); ?></nobr></td>
                    <td class="btn-actions-mini column-actions">
                        <a class="btn btn-info" href="<?= $this->url('users',
                            ['action'=>'edit', 'id'=>$user->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" ></span>
                        </a>
                        <a class="btn btn-default" title="Change Password" href="<?= $this->url('users',
                            ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                            <span class="glyphicon glyphicon-asterisk"></span>
                        </a>
                    </td>
                </tr>

            <?php endforeach; ?>

        </table>
    </div>
    <div class="col-md-12">
        <?= $this->paginationControl($this->users,
            'Sliding',
            'user/partial/paginator',
            array('route' => 'users')); ?>
    </div>
</div>
