<?php
$this->headTitle($this->translate('Reset Password'));

$this->form->get('email')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Email address')
]);

$this->form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
]);

$this->form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($this->form); ?>

        <h2><?= $this->translate('Reset Password')?></h2>

        <p><?= $this->translate('Enter your e-mail address below to reset your password')?></p>

        <?= $this->formElement($this->form->get('email')); ?>
        <?= $this->formElementErrors($this->form->get('email')); ?>

        <?= $this->formElement($this->form->get('captcha')); ?>
        <p class="hint"><?= $this->translate('Enter the letters above as you see them.')?></p>

        <?= $this->formElement($this->form->get('submit')); ?>

        <?= $this->formElement($this->form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
