<?php
$this->headTitle($this->translate('Set New Password'));

$this->form->get('new_password')->setAttributes(array(
    'class'       => 'form-control',
    'placeholder' => 'Type New Password'
));
$this->form->get('confirm_new_password')->setAttributes(array(
    'class'       => 'form-control',
    'placeholder' => $this->translate('Confirm New Password')
));
$this->form->get('submit')->setAttributes(array(
    'class'=>'btn btn-primary'
));
$this->form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($this->form); ?>

        <h2><?= $this->translate('Set New Password')?></h2>
        <p><?= $this->translate('Enter your new password in the form below');?></p>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('new_password')); ?>
            <?= $this->formElement($this->form->get('new_password')); ?>
            <?= $this->formElementErrors($this->form->get('new_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('confirm_new_password')); ?>
            <?= $this->formElement($this->form->get('confirm_new_password')); ?>
            <?= $this->formElementErrors($this->form->get('confirm_new_password')); ?>
        </div>

        <?= $this->formElement($this->form->get('submit')); ?>
        <?= $this->formElement($this->form->get('csrf')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
