<?php
$this->headTitle($this->translate('View User'));
$this->mainMenu()->setActiveItemId('users');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')         => $this->url('home'),
    $this->translate('Manage Users') => $this->url('users'),
    $this->translate('View User')    => $this->url('users', ['action'=>'view', 'id'=>$this->user->getId()])
]);
?>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1><?=$this->translate('View User')?> <?= $this->escapeHtml($this->user->getEmail()) ?></h1>

<p>
    <a class="btn btn-default" href="<?= $this->url('users',
            ['action'=>'edit', 'id'=>$this->user->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span>
        <?=$this->translate('Edit')?>
    </a>
    <a class="btn btn-default" href="<?= $this->url('users',
            ['action'=>'change-password', 'id'=>$this->user->getId()]); ?>">
        <span class="glyphicon glyphicon-asterisk"></span>
        <?=$this->translate('Change Password')?>
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($this->user->getId()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('E-mail')?>:</th>
                <td><?= $this->escapeHtml($this->user->getEmail()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Full Name')?>:</th>
                <td><?= $this->escapeHtml($this->user->getFullName()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Date Created')?>:</th>
                <td><?= $this->escapeHtml($this->user->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Status')?>:</th>
                <td><?= $this->escapeHtml($this->user->getStatusAsString()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Roles')?>:</th>
                <td><?= $this->escapeHtml($this->user->getRolesAsString()) ?></th>
            </tr>
        </table>
    </div>
</div>
