<?php
$this->headTitle('Add Post');

$this->mainMenu()->setActiveItemId('posts');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Posts'=>$this->url('posts'),
            'Add Post'=>$this->url('posts', ['action'=>'add'])
            ]);

$form->get('title')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Заполните титульный заголов поста'
    ]);

$form->get('content')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Add Post</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('content')); ?>
            <?= $this->formElement($form->get('content')); ?>
            <?= $this->formElementErrors($form->get('content')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->formElementErrors($form->get('csrf')); ?>
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

