<?php
$this->headTitle('Add Post');

$this->mainMenu()->setActiveItemId('posts');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Posts'=>$this->url('posts'),
            'Add Post'=>$this->url('posts', ['action'=>'add'])
            ]);

$this->form->get('title')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Заполните титульный заголов поста'
    ]);

$this->form->get('content')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
    ]);

if (!$this->access('post.manage')) {
    $this->form->get('status')->setAttributes([
        'class'    => 'form-control disabled-click',
    ]);
} else {
    $this->form->get('status')->setAttributes([
        'class'=>'form-control'
    ]);
}

$this->form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$this->form->prepare();
?>

<h1>Add Post</h1>

<p>Please fill out the following form and click the <i>Create</i> button.</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($this->form); ?>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('title')); ?>
            <?= $this->formElement($this->form->get('title')); ?>
            <?= $this->formElementErrors($this->form->get('title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('content')); ?>
            <?= $this->formElement($this->form->get('content')); ?>
            <?= $this->formElementErrors($this->form->get('content')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('status')); ?>
            <?= $this->formElement($this->form->get('status')); ?>
            <?= $this->formElementErrors($this->form->get('status')); ?>
        </div>

        <?= $this->formElement($this->form->get('csrf')); ?>
        <?= $this->formElementErrors($this->form->get('csrf')); ?>
        <?= $this->formElement($this->form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

