<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('posts');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')  => $this->url('home'),
    $this->translate('Posts') => $this->url('posts'),
]);
?>
<div class="row">
    <div class="col-md-12">
        <h1><?= $this->translate('Manage Posts');?></h1>

        <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
        <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
        <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

        <p>
            <a class="btn btn-default" href="<?= $this->url('posts', ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                <?= $this->translate('New Post');?>
            </a>
        </p>
    </div>
    <div class="col-md-12 scroll-x-auto">
        <table class="table table-striped table-condensed table-bordered min-width-table">

            <tr>
                <th class="column-id">ID</th>
                <th class="column-author crop"><?= $this->translate('Author')?></th>
                <th class="column-title crop"><?= $this->translate('Title')?></th>
                <th class="column-status"><?= $this->translate('Status')?></th>
                <th class="column-create"><?= $this->translate('Date Created')?></th>
                <th class="column-create"><?= $this->translate('Date Updated')?></th>
                <th class="column-actions"><?= $this->translate('Actions')?></th>
            </tr>

            <?php foreach ($this->posts as $post): ?>

                <tr>
                    <td class="column-id">
                        <span><?= $this->escapeHtml($post->getId()); ?></span>
                    </td>
                    <td class="column-author crop">
                        <span><?= $this->escapeHtml($post->getUser()->getFullName()); ?></span>
                    </td>
                    <td class="column-title crop">
                        <span><?= $this->escapeHtml($post->getTitle()); ?></span>
                    </td>
                    <td class="column-status"><span><?= $this->escapeHtml($post->getStatusAsString()); ?></span></td>
                    <td class="column-create"><nobr><?= $this->escapeHtml($post->getDateCreated()); ?></nobr></td>
                    <td class="column-create"><nobr><?= $this->escapeHtml($post->getDateUpdated()); ?></nobr></td>
                    <td class="btn-actions-mini column-actions"><nobr>
                        <a class="btn btn-info" href="<?= $this->url('posts',
                            ['action'=>'edit', 'id'=>$post->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" ></span>
                        </a>
                        <a class="btn btn-danger" href="<?= $this->url('posts',
                            ['action'=>'delete', 'id'=>$post->getId()]); ?>">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a></nobr>
                    </td>
                </tr>

            <?php endforeach; ?>

        </table>
    </div>
    <div class="col-md-12">
        <?= $this->paginationControl(
            $this->posts,
            'Sliding',
            'application/partial/paginator',
            array('route' => 'posts')
        ); ?>
    </div>
</div>





