<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('posts');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Posts'=>$this->url('posts'),
]);
?>

<h1>Manage Posts</h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('posts', ['action'=>'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Post
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Author</th>
        <th>Title</th>
        <th>Date Created</th>
        <th>Status</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($this->posts as $post): ?>

        <tr>
            <td><?= $this->escapeHtml($post->getId()); ?></td>
            <td>
                <?= $this->escapeHtml($post->getUser()->getFullName()); ?></a>
            </td>
            <td>
                <?= $this->escapeHtml($post->getTitle()); ?></a>
            </td>
            <td><nobr><?= $this->escapeHtml($post->getDateCreated()); ?></nobr></td>
            <td><?= $this->escapeHtml($post->getStatusAsString()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('posts',
                    ['action'=>'edit', 'id'=>$post->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span>
                </a>
                <a class="btn btn-danger" href="<?= $this->url('posts',
                    ['action'=>'delete', 'id'=>$post->getId()]); ?>">
                    <span class="glyphicon glyphicon-remove"></span>
                </a>
            </td>
        </tr>

    <?php endforeach; ?>

</table>

<?= $this->paginationControl(
        $this->posts,
        'Sliding',
        'application/partial/paginator',
        array('route' => 'posts')
    ); ?>




