<?php
$this->headTitle($this->translate('Edit Role'));
$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')         => $this->url('home'),
    $this->translate('Manage Roles') => $this->url('roles'),
    $this->translate('Edit Role')    => $this->url('roles', ['action'=>'edit', 'id'=>$this->role->getId()])
]);

$this->form->get('name')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Enter Name')
]);

$this->form->get('description')->setAttributes([
    'class'       => 'form-control',
    'placeholder' => $this->translate('Enter description')
]);

$this->form->get('inherit_roles')->setAttributes([
    'class'=>'form-control',
]);


$this->form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue('Save');

$this->form->prepare();
?>

<h1><?=$this->translate('Edit Role')?> <?= $this->escapeHtml($this->role->getName()) ?></h1>

<p>
<a class="btn btn-default" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$this->role->getId()]) ?>">
    <span class="glyphicon glyphicon-check"></span>
    <?=$this->translate('Edit Permissions')?>
</a>
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($this->form); ?>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('name')); ?>
            <?= $this->formElement($this->form->get('name')); ?>
            <?= $this->formElementErrors($this->form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('description')); ?>
            <?= $this->formElement($this->form->get('description')); ?>
            <?= $this->formElementErrors($this->form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('inherit_roles')); ?>
            <?= $this->formElement($this->form->get('inherit_roles')); ?>
            <?= $this->formElementErrors($this->form->get('inherit_roles')); ?>
        </div>

        <?= $this->formElement($this->form->get('csrf')); ?>
        <?= $this->formElement($this->form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

