<?php
$this->headTitle($this->translate('Edit Role Permissions'));
$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')         => $this->url('home'),
    $this->translate('Manage Roles') => $this->url('roles'),
    $this->translate('Edit Role')    => $this->url('roles', ['action'=>'edit', 'id' => $this->role->getId()])
]);

$this->form->get('submit')
    ->setAttributes(['class'=>'btn btn-primary'])
    ->setValue('Save');

$this->form->prepare();
?>

<h1><?=$this->translate('Edit Permissions of')?> <?= $this->escapeHtml($this->role->getName()) ?></h1>

<div class="row">
    <div class="col-md-8">
        <?= $this->form()->openTag($this->form); ?>
        <table class="table table-striped table-bordered">
            <tr>
                <th><?=$this->translate('Name')?></th>
                <th><?=$this->translate('Description')?></th>
            </tr>
            <?php foreach ($this->allPermissions as $permission):
                $element = $this->form->get('permissions')->get($permission->getName());
            ?>
            <tr>
                <td>
                    <div class="checkbox">
                        <label><input type="checkbox" name="<?= $this->escapeHtmlAttr($element->getName()) ?>"
                                      value="<?= $this->escapeHtmlAttr($element->getCheckedValue()) ?>"
                                      <?php if ($element->isChecked()) echo 'checked'?>
                                      <?php if ($element->getAttribute('disabled')) echo 'disabled'?>>
                            <?= $this->escapeHtml($element->getLabel()) ?>
                        </label>
                        <?= $this->formElementErrors($element); ?>
                    </div>
                </td>
                <td>
                    <?= $this->escapeHtml($permission->getDescription()) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?= $this->formElement($this->form->get('csrf')); ?>
        <?= $this->formElement($this->form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6"></div>
</div>

