<?php
$this->headTitle($this->translate('Roles'));
$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')         => $this->url('home'),
    $this->translate('Manage Roles') => $this->url('roles'),
]);
?>

<div class="row">
    <div class="col-md-12">
        <h1><?=$this->translate('Manage Roles')?></h1>

        <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
        <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
        <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

        <p>
            <a class="btn btn-default" href="<?= $this->url('roles', ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                <?=$this->translate('New Role')?>
            </a>
        </p>
    </div>
    <div class="col-md-12  scroll-x-auto">
        <table class="table table-striped table-condensed table-bordered min-width-table">
            <tr>
                <th class="column-id">ID</th>
                <th><?=$this->translate('Name')?></th>
                <th class="column-title"><?=$this->translate('Description')?></th>
                <th class="column-create"><?=$this->translate('Date Created')?></th>
                <th class="column-actions"><?=$this->translate('Actions')?></th>
            </tr>

            <?php foreach ($this->roles as $role): ?>

                <tr>
                    <td class="column-id"><?= $this->escapeHtml($role->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                            <?= $this->escapeHtml($role->getName()); ?>
                        </a>
                    </td>
                    <td class="column-title crop"><?= $this->escapeHtml($role->getDescription()); ?></a>
                    </td>
                    <td class="column-create"><nobr><?= $this->escapeHtml($role->getDateCreated()); ?></nobr></td>
                    <td class="btn-actions-mini column-actions">
                        </nobr>
                        <a class="btn btn-info" href="<?= $this->url('roles',
                            ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" ></span>
                        </a>
                        <a class="btn btn-danger" href="<?= $this->url('roles',
                            ['action'=>'delete', 'id'=>$role->getId()]); ?>">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                        </nobr>
                    </td>
                </tr>

            <?php endforeach; ?>

        </table>
    </div>
    <div class="col-md-12">
        <?= $this->paginationControl($this->roles,
            'Sliding',
            'user/partial/paginator',
            array('route' => 'roles')); ?>
    </div>
</div>




