<?php
$this->headTitle('Roles');

$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Roles'=>$this->url('roles'),
    ]);
?>

<div class="row">
    <div class="col-md-12">
        <h1>Manage Roles</h1>

        <?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
        <?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
        <?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

        <p>
            <a class="btn btn-default" href="<?= $this->url('roles', ['action'=>'add']); ?>">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Role
            </a>
        </p>
    </div>
    <div class="col-md-12  scroll-x-auto">
        <table class="table table-striped table-condensed min-width-table">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date Created</th>
                <th>Actions</th>
            </tr>

            <?php foreach ($this->roles as $role): ?>

                <tr>
                    <td><?= $this->escapeHtml($role->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('roles', ['action'=>'view', 'id'=>$role->getId()]); ?>">
                            <?= $this->escapeHtml($role->getName()); ?>
                        </a>
                    </td>
                    <td><?= $this->escapeHtml($role->getDescription()); ?></a>
                    </td>
                    <td><nobr><?= $this->escapeHtml($role->getDateCreated()); ?></nobr></td>
                    <td class="btn-actions-mini">
                        </nobr>
                        <a class="btn btn-info" href="<?= $this->url('roles',
                            ['action'=>'edit', 'id'=>$role->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" ></span>
                        </a>
                        <a class="btn btn-danger" href="<?= $this->url('roles',
                            ['action'=>'delete', 'id'=>$role->getId()]); ?>">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                        </nobr>
                    </td>
                </tr>

            <?php endforeach; ?>

        </table>
    </div>
    <div class="col-md-12">
        <?= $this->paginationControl($this->roles,
            'Sliding',
            'user/partial/paginator',
            array('route' => 'roles')); ?>
    </div>
</div>




