<?php
$this->headTitle($this->translate('View Role'));
$this->mainMenu()->setActiveItemId('roles');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')         => $this->url('home'),
    $this->translate('Manage Roles') => $this->url('roles'),
    $this->translate('View Role')    => $this->url('roles', ['action'=>'view', 'id'=>$this->role->getId()])
]);
?>


<h1><?=$this->translate('View Role')?> <?= $this->escapeHtml($this->role->getName()) ?></h1>

<?= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<p>
<a class="btn btn-default" href="<?= $this->url('roles', ['action'=>'edit', 'id'=>$this->role->getId()]); ?>">
    <span class="glyphicon glyphicon-pencil" ></span>
    <?=$this->translate('Edit Role')?>
</a>
</p>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($this->role->getId()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Name')?>:</th>
                <td><?= $this->escapeHtml($this->role->getName()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Description')?>:</th>
                <td><?= $this->escapeHtml($this->role->getDescription()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Date Created')?>:</th>
                <td><?= $this->escapeHtml($this->role->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>

<h2><?=$this->translate('Permissions')?></h2>

<p>
<a class="btn btn-default" href="<?= $this->url('roles', ['action'=>'editPermissions', 'id'=>$this->role->getId()]) ?>">
    <span class="glyphicon glyphicon-check"></span>
    <?=$this->translate('Edit Permissions')?>
</a>
</p>

<div class="row">
    <div class="col-md-8">
        <table class="table table-striped table-bordered">
            <tr>
                <th><?=$this->translate('Name')?></th>
                <th><?=$this->translate('Description')?></th>
            </tr>
            <?php foreach($this->allPermissions as $permission): ?>
            <tr>
                <td>
                    <input type="checkbox" disabled <?php if (isset($effectivePermissions[$permission->getName()])) echo 'checked'; ?>>
                    <?= $this->escapeHtml($permission->getName()) ?>
                    <?php if (isset($effectivePermissions[$permission->getName()]) && $effectivePermissions[$permission->getName()]=='inherited'): ?>
                    <em>(inherited)</em>
                    <?php endif; ?>
                </td>
                <td><?= $this->escapeHtml($permission->getDescription()) ?></td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
