<?php
$this->headTitle($this->translate('Add Permission'));
$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')               => $this->url('home'),
    $this->translate('Manage Permissions') => $this->url('permissions'),
    $this->translate('Add Permission')     => $this->url('permissions', ['action'=>'add'])
]);

$this->form->get('name')->setAttributes([
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter Name')
]);

$this->form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => $this->translate('Enter description')
]);

$this->form->get('submit')
    ->setAttributes(['class'=>'btn btn-primary'])
    ->setValue($this->translate('Create'));
$this->form->prepare();
?>

<h1><?=$this->translate('Add Permission')?></h1>

<p>
<?=$this->translate('Please fill out the following form and click the <i>Create</i> button.')?>
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($this->form); ?>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('name')); ?>
            <?= $this->formElement($this->form->get('name')); ?>
            <?= $this->formElementErrors($this->form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($this->form->get('description')); ?>
            <?= $this->formElement($this->form->get('description')); ?>
            <?= $this->formElementErrors($this->form->get('description')); ?>
        </div>

        <?= $this->formElement($this->form->get('csrf')); ?>
        <?= $this->formElement($this->form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>



