<?php
$this->headTitle($this->translate('View Permission'));
$this->mainMenu()->setActiveItemId('permissions');

$this->pageBreadcrumbs()->setItems([
    $this->translate('Home')               => $this->url('home'),
    $this->translate('Manage Permissions') => $this->url('permissions'),
    $this->translate('View Permission')    => $this->url('permissions', ['action'=>'view', 'id'=>$this->permission->getId()])
]);
?>

<h1><?=$this->translate('View Permission')?></h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($this->permission->getId()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Name')?>:</th>
                <td><?= $this->escapeHtml($this->permission->getName()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Description')?>:</th>
                <td><?= $this->escapeHtml($this->permission->getDescription()) ?></th>
            </tr>
            <tr>
                <th><?=$this->translate('Date Created')?>:</th>
                <td><?= $this->escapeHtml($this->permission->getDateCreated()) ?></th>
            </tr>
        </table>
    </div>
</div>
